name: learn-github-actions
on: [push]
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "run tests job"
  push-to-ecr:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - run: echo "push to ECR job"
