name: smoke-tests-spike
on:
  push:
    branches: [ spike_create_github_actions_smoke_test_pipeline ]
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7.x]
    steps:
      - run: echo "run tests job"
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
  push-to-ecr:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - run: echo "push to ECR job"
